server:
  port: 8090

spring:
  application:
    name: mscv-course
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/courses_db?authSource=admin
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
